import { Product, Prisma } from '@prisma/client';

export const mockProducts: Omit<Product, 'id'>[] = [
  {
    name: 'Mock product 1',
    description: 'Mock product 1',
    price: new Prisma.Decimal(101),
    tags: 'tag1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 2',
    description: 'Mock product 2',
    price: new Prisma.Decimal(102),
    tags: 'tag3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 3',
    description: 'Mock product 3',
    price: new Prisma.Decimal(103),
    tags: 'tag3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 4',
    description: 'Mock product 4',
    price: new Prisma.Decimal(104),
    tags: 'tag4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 5',
    description: 'Mock product 5',
    price: new Prisma.Decimal(105),
    tags: 'tag5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 6',
    description: 'Mock product 6',
    price: new Prisma.Decimal(106),
    tags: 'tag6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 7',
    description: 'Mock product 7',
    price: new Prisma.Decimal(107),
    tags: 'tag7',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 8',
    description: 'Mock product 8',
    price: new Prisma.Decimal(108),
    tags: 'tag8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 9',
    description: 'Mock product 9',
    price: new Prisma.Decimal(109),
    tags: 'tag9',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 10',
    description: 'Mock product 10',
    price: new Prisma.Decimal(110),
    tags: 'tag10',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mock product 11',
    description: 'Mock product 11',
    price: new Prisma.Decimal(111),
    tags: 'tag11',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]
